# Default prompts and shared snippets
# Shared snippets can be referenced in prompts using {variable_name}

shared:
  zh-CN:
    image_placeholder: "[IMAGE: filename.png]"
    output_requirements: "对话文本必须为纯文本（不包括表情符号、特殊字符等），结构清晰。不改变任何原始含义并保留所有信息。输出必须是结构良好、层次清晰的纯文本，不包含任何额外的解释、摘要或多余内容。"
    content_processing: "完全保留和描述所有内容，不遗漏任何信息。必要时使用Markdown格式处理代码或引用内容（例如，``` 用于代码块，> 用于引用）。"

  en-US:
    image_placeholder: "[IMAGE: filename.png]"
    output_requirements: "Conversation text must be plain text (excluding emojis, special characters, etc.) with clear structure. Without altering any original meaning and retaining all information. Output must be well-structured, hierarchically clear plain text, without any additional explanations, summaries, or extra content."
    content_processing: "Fully retain and describe all content without omission. Using Markdown formatting when necessary for code or quoted content (e.g., ``` for code blocks, > for quotes)."

# Common prompts (language-agnostic)
# These prompts are used for all languages
common:
  email_content_prompt: |
    Please output in {language}.

    Your task is to organize the provided content — which may include email threads, chat logs, or message exchanges — into a standardized Markdown-formatted conversation for archival and easy reference.
    Ensure the output preserves all original information while presenting it in a clean, consistent, and chronological structure (from the earliest to the latest).
    Apply minimal editing only to improve readability, and clearly mark any assumptions.

    Output Format (Markdown):

    Each message must strictly follow this format:

    - Speaker (Date Time)
    Message content

    Additional rules:

    Date and Time
    - If the date is unknown, display only the time.
    - If known, include both date and time in a consistent format (e.g., 2025-10-22 14:05).

    Images
    - Use placeholders in the format [IMAGE: filename.png], placed on a separate line in their original position.

    Plain Text Only
    - The conversation must contain plain text only (no emojis, markdown decorations, or special characters).

    No Additional Commentary
    - Do not include explanations, analysis, or summaries outside of the formatted conversation.

  ocr_prompt: |
    Please output in {language}.

    Your task is to CLEAN and ORGANIZE OCR-recognized content, making it more readable and well-structured while remaining faithful to the original OCR text. DO NOT add interpretations, explanations, or extra information beyond what is present in the OCR results.

    Task Objectives:

    Complete Information Preservation
    - Include ALL OCR content regardless of whether it seems relevant or not.
    - Do NOT filter out any text based on relevance judgment.
    - Describe everything visible in the screenshot: titles, menus, toolbars, status bars, buttons, labels, etc.
    - Even if some content appears to be UI elements or seems unrelated, still include it in your output.
    - Keep all numbers, codes, timestamps, and identifiers exactly as they appear.

    Clean and Organize OCR Text
    - Correct obvious OCR errors (e.g., "1" → "I", "rn" → "m") when the correct word is clear from context.
    - Fix spacing issues (combine split words, add missing spaces).
    - Remove redundant repeated characters or artifacts.
    - Organize text into logical paragraphs or sections based on the original structure.

    Preserve Original Content
    - DO NOT add interpretations, explanations, or supplementary information beyond what is in the OCR text.
    - DO NOT expand brief notes into detailed descriptions (unless it's a list/table that needs language conversion).
    - DO NOT translate specialized terms or brand names.
    - If the OCR text is incomplete or unclear, keep it as-is without adding speculation.

    Maintain Accuracy
    - Keep proper nouns, technical terms, product names, and brand names in their original language. Do not translate them (e.g., keep "CPU", "AWS", "Kubernetes", "Chrome" as-is, even when outputting in Chinese).
    - Preserve all numbers, dates, and technical data exactly as they appear.
    - If OCR result is ambiguous, mark uncertain parts but do not add explanations.

    Output Format
    - Output clean, well-structured text that mirrors the original content's organization.
    - For lists: convert bullet points or numbered items into natural language sentences that describe each item.
    - For tables: describe the information in natural language, mentioning row and column relationships when relevant.
    - For documents: maintain the original hierarchy (titles, sections, paragraphs).
    - Do NOT add summaries, conclusions, or commentary beyond what is present in the OCR text.
    - Do NOT expand on what the original text says or speculate about missing information.

    Critical Rules
    - If the OCR text is incomplete or ends abruptly, output exactly what is there without adding anything. Do NOT suggest what might have followed or what the complete version could be.
    - NEVER omit content because you think it's "not relevant" or "UI noise". Screenshots often include important context in UI elements, headers, footers, and status indicators.
    - Completeness is more important than relevance - your job is to clean and organize, not to filter content.

  summary_title_prompt: |
    Please output in {language}.

    Extract a single concise title from the provided chat records.

    Requirements:
    - The title must accurately capture the core topic, problem, or discussion point
    - Use clear, specific language. Avoid vague terms
    - Maximum length: 200 characters
    - If multiple topics exist, extract only the most critical and central one
    - Generate only the title text without any prefixes, tags, or brackets
    - Do not add explanations, summaries, or any additional text
