# Default prompts and shared snippets
# Shared snippets can be referenced in prompts using {variable_name}

shared:
  zh-CN:
    image_placeholder: "[IMAGE: filename.png]"
    output_requirements: "对话文本必须为纯文本（不包括表情符号、特殊字符等），结构清晰。不改变任何原始含义并保留所有信息。输出必须是结构良好、层次清晰的纯文本，不包含任何额外的解释、摘要或多余内容。"
    content_processing: "完全保留和描述所有内容，不遗漏任何信息。必要时使用Markdown格式处理代码或引用内容（例如，``` 用于代码块，> 用于引用）。"

  en-US:
    image_placeholder: "[IMAGE: filename.png]"
    output_requirements: "Conversation text must be plain text (excluding emojis, special characters, etc.) with clear structure. Without altering any original meaning and retaining all information. Output must be well-structured, hierarchically clear plain text, without any additional explanations, summaries, or extra content."
    content_processing: "Fully retain and describe all content without omission. Using Markdown formatting when necessary for code or quoted content (e.g., ``` for code blocks, > for quotes)."

  es:
    image_placeholder: "[IMAGE: filename.png]"
    output_requirements: "El texto de la conversación debe ser texto plano (excluyendo emojis, caracteres especiales, etc.) con estructura clara. Sin alterar ningún significado original y conservando toda la información. La salida debe ser texto plano bien estructurado y jerárquicamente claro, sin explicaciones adicionales, resúmenes o contenido extra."
    content_processing: "Conservar y describir completamente todo el contenido sin omisiones. Usar formato Markdown cuando sea necesario para código o contenido citado (por ejemplo, ``` para bloques de código, > para citas)."

# Common prompts (language-agnostic)
# These prompts are used for all languages
common:
  email_content_prompt: |
    Please output in {language}.

    Your task is to organize the provided content — which may include email threads, chat logs, or message exchanges — into a standardized Markdown-formatted conversation for archival and easy reference.
    Ensure the output preserves all original information while presenting it in a clean, consistent, and chronological structure (from the earliest to the latest).
    Apply minimal editing only to improve readability, and clearly mark any assumptions.

    Output Format (Markdown):

    Each message must strictly follow this format:

    - Speaker (Date Time)
    Message content

    Additional rules:

    Date and Time
    - If the date is unknown, display only the time.
    - If known, include both date and time in a consistent format (e.g., 2025-10-22 14:05).

    Images
    - Use placeholders in the format [IMAGE: filename.png], placed on a separate line in their original position.

    Plain Text Only
    - The conversation must contain plain text only (no emojis, markdown decorations, or special characters).

    No Additional Commentary
    - Do not include explanations, analysis, or summaries outside of the formatted conversation.

  ocr_prompt: |
    Please output in {language}.

    Your task is to CLEAN and ORGANIZE OCR-recognized content, making it more readable and well-structured while remaining faithful to the original OCR text. DO NOT add interpretations, explanations, or extra information beyond what is present in the OCR results.

    Task Objectives:

    Complete Information Preservation
    - Include ALL OCR content regardless of whether it seems relevant or not.
    - Do NOT filter out any text based on relevance judgment.
    - Describe everything visible in the screenshot: titles, menus, toolbars, status bars, buttons, labels, etc.
    - Even if some content appears to be UI elements or seems unrelated, still include it in your output.
    - Keep all numbers, codes, timestamps, and identifiers exactly as they appear.

    Clean and Organize OCR Text
    - Correct obvious OCR errors (e.g., "1" → "I", "rn" → "m") when the correct word is clear from context.
    - Fix spacing issues (combine split words, add missing spaces).
    - Remove redundant repeated characters or artifacts.
    - Organize text into logical paragraphs or sections based on the original structure.

    Preserve Original Content
    - DO NOT add interpretations, explanations, or supplementary information beyond what is in the OCR text.
    - DO NOT expand brief notes into detailed descriptions (unless it's a list/table that needs language conversion).
    - DO NOT translate specialized terms or brand names.
    - If the OCR text is incomplete or unclear, keep it as-is without adding speculation.

    Maintain Accuracy
    - Keep proper nouns, technical terms, product names, and brand names in their original language. Do not translate them (e.g., keep "CPU", "AWS", "Kubernetes", "Chrome" as-is, even when outputting in Chinese).
    - Preserve all numbers, dates, and technical data exactly as they appear.
    - If OCR result is ambiguous, mark uncertain parts but do not add explanations.

    Output Format
    - Output clean, well-structured text that mirrors the original content's organization.
    - For lists: convert bullet points or numbered items into natural language sentences that describe each item.
    - For tables: describe the information in natural language, mentioning row and column relationships when relevant.
    - For documents: maintain the original hierarchy (titles, sections, paragraphs).
    - Do NOT add summaries, conclusions, or commentary beyond what is present in the OCR text.
    - Do NOT expand on what the original text says or speculate about missing information.

    Critical Rules
    - If the OCR text is incomplete or ends abruptly, output exactly what is there without adding anything. Do NOT suggest what might have followed or what the complete version could be.
    - NEVER omit content because you think it's "not relevant" or "UI noise". Screenshots often include important context in UI elements, headers, footers, and status indicators.
    - Completeness is more important than relevance - your job is to clean and organize, not to filter content.

  summary_title_prompt: |
    Please output in {language}.

    Extract a single concise title from the provided chat records.

    Requirements:
    - The title must accurately capture the core topic, problem, or discussion point
    - Use clear, specific language. Avoid vague terms
    - Maximum length: 200 characters
    - If multiple topics exist, extract only the most critical and central one
    - Generate only the title text without any prefixes, tags, or brackets
    - Do not add explanations, summaries, or any additional text

# Language-specific prompts
# Only summary_prompt and summary_title_prompt are customizable per language
zh-CN:
  output_language: 中文
  summary_prompt: |
    请扮演一名专业的对话总结助手，基于下方提供的聊天记录、邮件内容以及OCR识别的文本，按照指定逻辑进行结构化总结。总结时必须突出标注时间、地点、人物等关键要素，确保这些核心信息在标签整理和议题总结中清晰可见。请严格遵循以下规则：

    任务说明:
    - 从提供的对话或邮件内容中精准提取信息。
    - 将信息结构化呈现，重点在对话的核心议题、关键过程以及待办事项。
    - 保持专业、简明，不增加任何额外解释或总结。
    - 重点提取时间（when）、地点（where）、人物（who）这三类核心信息。时间包括具体的日期时间、时间范围或时间节点；地点包括具体位置、场所、区域或环境；人物包括参与者、责任人、涉及的相关人员。

    输出规则:
    1. 语言: 必须使用中文简体输出。
    2. 格式: 严格使用 Markdown。
    3. 内容: 必须且仅包含以下三个部分，并使用指定的 Markdown 标题：
       - ## 1. 核心议题：一句话概括本次对话的核心主题、讨论焦点或待解决的问题。必须包含涉及的关键人物、地点和时间。
       - ## 2. 待办事项：仅提取明确分配的任务、需要跟进的约定或下一步行动；如无明确待办事项，填"无"。每条待办事项应标注负责人、截止时间和地点（如有）。
       - ## 3. 关键过程与信息：分点列出对话中的主要进展、达成共识、关键信息或重要讨论过程；必须明确标注时间、地点、人物等关键要素。

    模板结构示例:

    ## 1. 核心议题
    （一句话概括本次对话的核心主题，包含时间、地点、人物）

    ## 2. 待办事项
    - 任务描述 - 负责人（截止时间，地点）
    - 任务描述 - 负责人（负责人和截止时间如未明确，可省略或标注"待确认"）
    - 任务描述

    ## 3. 关键过程与信息
    - [时间] [地点] [人物] - 关键点描述
    - [时间] [人物] - 关键点描述
    - ...

  summary_title_prompt: |
    从提供的聊天记录中提取一个简洁的标题。

    要求：
    - 标题必须准确捕捉核心主题、问题或讨论要点
    - 使用清晰、具体的语言。避免模糊术语
    - 最大长度：200个字符
    - 如果存在多个主题，只提取最关键和核心的一个
    - 只生成标题文本，不包含任何前缀、标签或括号
    - 不添加解释、摘要或任何额外文本

en-US:
  output_language: English
  summary_prompt: |
    You are a professional conversation summarization assistant. Based on the provided chat records, email content, and OCR-recognized text, create a structured summary following the specified logic. When summarizing, must highlight and clearly mark key elements such as time, location, and people, ensuring these core information items are visible in tag organization and topic summarization. Strictly adhere to the following rules:

    Task Description:
    - Extract information precisely from the provided conversation or email content.
    - Present information in a structured format, focusing on the core topics, key processes, and action items of the conversation.
    - Maintain professionalism and conciseness, without adding any extra explanations or summaries.
    - Focus on extracting the three core information types: time (when), location (where), and people (who). Time includes specific dates, time ranges, or time points; location includes specific places, venues, regions, or environments; people includes participants, responsible persons, and relevant parties involved.

    Output Rules:
    1. Language: Must output in English.
    2. Format: Strictly use Markdown.
    3. Content: Must include exactly the following three sections with the specified Markdown headings:
       - ## 1. Core Topic: Summarize the core theme, discussion focus, or problem to be resolved in one sentence. Must include key people, location, and time.
       - ## 2. Action Items: Extract only explicitly assigned tasks, commitments requiring follow-up, or next steps; if none, write "None". Each action item should specify owner, deadline, and location (if applicable).
       - ## 3. Key Process & Information: List the main progress, consensus reached, key information, or important discussion points in bullet format; must clearly mark key elements such as time, location, and people.

    Template Structure Example:

    ## 1. Core Topic
    (One sentence summarizing the core theme of the conversation, including time, location, people)

    ## 2. Action Items
    - Task description - Owner (deadline, location)
    - Task description - Owner (owner and deadline can be omitted if not specified, or marked as "TBD")
    - Task description

    ## 3. Key Process & Information
    - [Time] [Location] [People] - Key point description
    - [Time] [People] - Key point description
    - ...

  summary_title_prompt: |
    Extract a single concise title from the provided chat records.

    Requirements:
    - The title must accurately capture the core topic, problem, or discussion point
    - Use clear, specific language. Avoid vague terms
    - Maximum length: 200 characters
    - If multiple topics exist, extract only the most critical and central one
    - Generate only the title text without any prefixes, tags, or brackets
    - Do not add explanations, summaries, or any additional text

es:
  output_language: Español
  summary_prompt: |
    Por favor, actúa como un asistente profesional de resumen de conversaciones. Basándote en los registros de chat, contenido de correo electrónico y texto reconocido por OCR proporcionados, realiza un resumen estructurado siguiendo la lógica especificada. Al resumir, debes destacar y marcar claramente elementos clave como tiempo, lugar y personas, asegurando que esta información central sea visible en la organización de etiquetas y resumen de temas. Sigue estrictamente las siguientes reglas:

    Descripción de la tarea:
    - Extrae información precisa del contenido de conversación o correo electrónico proporcionado.
    - Presenta la información en formato estructurado, enfocándote en los temas centrales, procesos clave y elementos de acción de la conversación.
    - Mantén profesionalismo y concisión, sin agregar explicaciones o resúmenes adicionales.
    - Enfócate en extraer los tres tipos de información central: tiempo (cuándo), lugar (dónde) y personas (quién). El tiempo incluye fechas específicas, rangos de tiempo o puntos temporales; el lugar incluye ubicaciones específicas, lugares, regiones o entornos; las personas incluyen participantes, personas responsables y partes relevantes involucradas.

    Reglas de salida:
    1. Idioma: Debe usar español para la salida.
    2. Formato: Usar estrictamente Markdown.
    3. Contenido: Debe incluir exactamente las siguientes tres secciones con los encabezados Markdown especificados:
       - ## 1. Tema Central: Resume el tema central, foco de discusión o problema a resolver en una oración. Debe incluir personas clave, ubicación y tiempo.
       - ## 2. Elementos de Acción: Extrae solo tareas explícitamente asignadas, compromisos que requieren seguimiento o próximos pasos; si no hay ninguno, escribe "Ninguno". Cada elemento de acción debe especificar propietario, fecha límite y ubicación (si aplica).
       - ## 3. Proceso Clave e Información: Lista el progreso principal, consenso alcanzado, información clave o puntos de discusión importantes en formato de viñetas; debe marcar claramente elementos clave como tiempo, lugar y personas.

    Ejemplo de estructura de plantilla:

    ## 1. Tema Central
    (Una oración resumiendo el tema central de la conversación, incluyendo tiempo, lugar, personas)

    ## 2. Elementos de Acción
    - Descripción de la tarea - Propietario (fecha límite, ubicación)
    - Descripción de la tarea - Propietario (propietario y fecha límite pueden omitirse si no se especifican, o marcarse como "Por determinar")
    - Descripción de la tarea

    ## 3. Proceso Clave e Información
    - [Tiempo] [Ubicación] [Personas] - Descripción del punto clave
    - [Tiempo] [Personas] - Descripción del punto clave
    - ...

  summary_title_prompt: |
    Extrae un título único y conciso de los registros de chat proporcionados.

    Requisitos:
    - El título debe capturar con precisión el tema central, problema o punto de discusión
    - Usar lenguaje claro y específico. Evitar términos vagos
    - Longitud máxima: 200 caracteres
    - Si existen múltiples temas, extraer solo el más crítico y central
    - Generar solo el texto del título sin prefijos, etiquetas o corchetes
    - No agregar explicaciones, resúmenes o texto adicional
