# Product Issue scenario prompts
# All prompts are now unified in common section of default.yaml
# This file is kept for future scene-specific customizations if needed
# Currently uses common prompts from default.yaml with {language} variable

# If scene-specific summary_prompt is needed in the future, it can be added here:
# common:
#   summary_prompt: |
#     Please output in {language}.
#     You are a product manager...
#
# This would override the default common summary_prompt for this scenario only
