# Generated by Django 5.1.4 on 2025-08-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0006_remove_emailmessage_stage_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='processing_stage',
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
