# Generated by Django 5.1.4 on 2025-08-19 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0007_add_updated_at_to_emailattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ocr_processing', 'OCR Processing'), ('ocr_success', 'OCR Success'), ('ocr_failed', 'OCR Failed'), ('ocr_skipped', 'OCR Skipped'), ('llm_processing', 'LLM Processing'), ('llm_success', 'LLM Success'), ('llm_failed', 'LLM Failed'), ('llm_skipped', 'LLM Skipped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32, verbose_name='Processing Status'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['status'], name='jirabot_ema_status_039dc8_idx'),
        ),
    ]
