# Generated by Django 5.1.4 on 2025-08-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0009_set_initial_attachment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ocr_processing', 'OCR Processing'), ('ocr_success', 'OCR Success'), ('ocr_failed', 'OCR Failed'), ('llm_processing', 'LLM Processing'), ('llm_success', 'LLM Success'), ('llm_failed', 'LLM Failed')], db_index=True, default='pending', max_length=32, verbose_name='Processing Status'),
        ),
    ]
