# Generated by Django 5.1.4 on 2026-05-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="relaydelivery",
            new_name="relay_relay_event_i_0f5a98_idx",
            old_name="relay_deliv_event_s_9f4e94_idx",
        ),
        migrations.RenameIndex(
            model_name="relaydelivery",
            new_name="relay_relay_subscri_77dfc9_idx",
            old_name="relay_deliv_subsc_7d9a7e_idx",
        ),
        migrations.RenameIndex(
            model_name="relaydelivery",
            new_name="relay_relay_target__5e8a33_idx",
            old_name="relay_deliv_targe_0cae13_idx",
        ),
        migrations.RenameIndex(
            model_name="relayevent",
            new_name="relay_relay_user_id_92c8e3_idx",
            old_name="relay_event_user_st_7b4a71_idx",
        ),
        migrations.RenameIndex(
            model_name="relayevent",
            new_name="relay_relay_event_t_d92b47_idx",
            old_name="relay_event_type_st_4a7a38_idx",
        ),
        migrations.RenameIndex(
            model_name="relaysubscription",
            new_name="relay_relay_user_id_5d4979_idx",
            old_name="relay_subs_user_en_6f1bb4_idx",
        ),
        migrations.RenameIndex(
            model_name="relaysubscription",
            new_name="relay_relay_user_id_5e4894_idx",
            old_name="relay_subs_user_ta_5cd601_idx",
        ),
    ]
