# Generated by Django 5.1.4 on 2025-10-17 03:45

from django.db import migrations, models


def migrate_wechat_to_socialaccount(apps, schema_editor):
    """
    Data migration: Migrate WeChat users to django-allauth SocialAccount.

    Moves existing WeChat authentication data (openid/unionid) from Profile
    to SocialAccount, following Django community best practices.
    """
    Profile = apps.get_model('accounts', 'Profile')
    SocialAccount = apps.get_model('socialaccount', 'SocialAccount')

    migrated_count = 0

    for profile in Profile.objects.exclude(openid=''):
        if not SocialAccount.objects.filter(
            user=profile.user,
            provider='weixin'
        ).exists():
            SocialAccount.objects.create(
                user=profile.user,
                provider='weixin',
                uid=profile.openid,
                extra_data={
                    'unionid': profile.unionid if profile.unionid else '',
                    'migrated_from_profile': True
                }
            )
            migrated_count += 1

    if migrated_count > 0:
        print(
            f"✓ Migrated {migrated_count} WeChat user(s) "
            f"from Profile to SocialAccount"
        )


def initialize_user_preferences(apps, schema_editor):
    """
    Data migration: Initialize preferences for existing users.

    Sets default timezone and marks all existing users as having
    completed registration for backward compatibility.
    """
    Profile = apps.get_model('accounts', 'Profile')

    updated_count = Profile.objects.filter(
        registration_completed=False
    ).update(
        registration_completed=True,
        timezone='Asia/Shanghai'
    )

    if updated_count > 0:
        print(
            f"✓ Initialized {updated_count} existing profile(s): "
            f"registration_completed=True, timezone=Asia/Shanghai"
        )


def reverse_migrations(apps, schema_editor):
    """
    Reverse migration: Clean up migrated data.

    Note: This is for development purposes only.
    """
    SocialAccount = apps.get_model('socialaccount', 'SocialAccount')
    SocialAccount.objects.filter(
        provider='weixin',
        extra_data__migrated_from_profile=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('socialaccount', '__latest__'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether user has completed the registration process (set password, virtual email, scene selection).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_token',
            field=models.CharField(blank=True, db_index=True, help_text='Temporary token for email registration verification. Expires after REGISTRATION_TOKEN_EXPIRY_HOURS.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration datetime for registration_token.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for displaying dates and times. Common values: 'UTC', 'Asia/Shanghai', 'America/New_York', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL link to the user's avatar."),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Personal biography or description.', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('zh-CN', '简体中文')], default='en-US', help_text="User's preferred language for UI and notifications. This is a global setting shared across all applications.", max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, help_text='User nickname.', max_length=30),
        ),
        migrations.RunPython(
            migrate_wechat_to_socialaccount,
            reverse_code=reverse_migrations
        ),
        migrations.RunPython(
            initialize_user_preferences,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='openid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unionid',
        ),
    ]
