# Generated by Django 5.1.4 on 2025-07-24 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Task Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('emails_processed', models.IntegerField(default=0, verbose_name='Emails Processed')),
                ('emails_created_issues', models.IntegerField(default=0, verbose_name='Issues Created')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Task',
                'verbose_name_plural': 'Email Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Unique email message ID', max_length=255, verbose_name='Message ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('sender', models.EmailField(max_length=254, verbose_name='Sender')),
                ('recipients', models.TextField(help_text='Comma-separated list of recipients', verbose_name='Recipients')),
                ('received_at', models.DateTimeField(verbose_name='Received At')),
                ('raw_content', models.TextField(help_text='Original email content', verbose_name='Raw Content')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML Content')),
                ('text_content', models.TextField(blank=True, verbose_name='Text Content')),
                ('summary_title', models.CharField(blank=True, max_length=200, verbose_name='Summary Title')),
                ('summary_content', models.TextField(blank=True, verbose_name='Summary Content')),
                ('summary_priority', models.CharField(blank=True, max_length=20, verbose_name='Summary Priority')),
                ('llm_content', models.TextField(blank=True, help_text='Content organized by large language model', null=True, verbose_name='LLM Processed Content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('ocr_processing', 'OCR Processing'), ('ocr_failed', 'OCR Failed'), ('ocr_success', 'OCR Success'), ('summary_processing', 'Summary Processing'), ('summary_failed', 'Summary Failed'), ('summary_success', 'Summary Success'), ('jira_processing', 'JIRA Processing'), ('jira_failed', 'JIRA Failed'), ('jira_success', 'JIRA Success'), ('attachment_uploading', 'Attachment Uploading'), ('attachment_upload_failed', 'Attachment Upload Failed'), ('attachment_uploaded', 'Attachment Uploaded'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=32, verbose_name='Processing Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='threadline.emailtask', verbose_name='Email Task')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_issue_key', models.CharField(help_text='JIRA issue key (e.g., PROJ-123)', max_length=50, verbose_name='JIRA Issue Key')),
                ('jira_url', models.URLField(verbose_name='JIRA Issue URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='threadline.emailmessage', verbose_name='Email Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'JIRA Issue',
                'verbose_name_plural': 'JIRA Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key name', max_length=100, verbose_name='Setting Key')),
                ('value', models.JSONField(help_text='Configuration value (JSON format)', verbose_name='Setting Value')),
                ('description', models.CharField(blank=True, help_text='Description of this setting', max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['user', 'key'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('file_size', models.IntegerField(verbose_name='File Size (bytes)')),
                ('file_path', models.CharField(help_text='Path to stored file', max_length=500, verbose_name='File Path')),
                ('is_image', models.BooleanField(default=False, help_text='Whether this attachment is an image', verbose_name='Is Image')),
                ('ocr_content', models.TextField(blank=True, help_text='Text content recognized from image attachment', null=True, verbose_name='OCR Content')),
                ('llm_content', models.TextField(blank=True, help_text='Content organized by large language model based on OCR result', null=True, verbose_name='LLM Processed Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attachments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='threadline.emailmessage', verbose_name='Email Message')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ['filename'],
                'indexes': [models.Index(fields=['user', 'is_image'], name='threadline_ema_user_id_4c1b2d_idx'), models.Index(fields=['email_message'], name='threadline_ema_email_m_8b422f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['user', 'status'], name='threadline_ema_user_id_5de46c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['created_at'], name='threadline_ema_created_5e5052_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'message_id'], name='threadline_ema_user_id_6103f8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'status'], name='threadline_ema_user_id_a39e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['received_at'], name='threadline_ema_receive_9598e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('user', 'message_id')},
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['user', 'email_message'], name='threadline_jir_user_id_106619_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['jira_issue_key'], name='threadline_jir_jira_is_55f7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['user', 'key'], name='threadline_set_user_id_9b038e_idx'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['is_active'], name='threadline_set_is_acti_98c632_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='settings',
            unique_together={('user', 'key')},
        ),
    ]
