# Generated by Django 5.1.4 on 2025-09-17 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Email alias name (without domain)', max_length=255, verbose_name='Alias')),
                ('domain', models.CharField(help_text='Email domain for this alias', max_length=255, verbose_name='Domain')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alias is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='User who owns this email alias', on_delete=django.db.models.deletion.CASCADE, related_name='email_aliases', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Alias',
                'verbose_name_plural': 'Email Aliases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alias', 'domain'], name='threadline__alias_510f14_idx'), models.Index(fields=['user', 'is_active'], name='threadline__user_id_6598ad_idx'), models.Index(fields=['created_at'], name='threadline__created_411fb4_idx')],
                'unique_together': {('alias', 'domain')},
            },
        ),
    ]
