# Generated by Django 5.1.4 on 2025-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0002_alter_emailmessage_summary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='safe_filename',
            field=models.CharField(blank=True, help_text='UUID-based filename for file system storage', max_length=255, null=True, verbose_name='Safe Filename'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='filename',
            field=models.CharField(help_text='Original filename from email', max_length=255, verbose_name='Filename'),
        ),
    ]
