# Generated by Django 5.1.4 on 2025-09-28 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0002_add_email_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtask',
            name='details',
            field=models.JSONField(default=list, help_text='Detailed execution log and status information', verbose_name='Execution Details'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='email_source',
            field=models.CharField(choices=[('IMAP_EMAIL_FETCH', 'IMAP Email Fetch'), ('HARAKA_EMAIL_FETCH', 'Haraka Email Fetch')], default='IMAP_EMAIL_FETCH', help_text='Type of email source being processed', max_length=20, verbose_name='Email Source'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255, verbose_name='Celery Task ID'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='timeout_seconds',
            field=models.IntegerField(default=600, help_text='Task timeout in seconds (default: 10 minutes)', verbose_name='Timeout Seconds'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User for user-specific tasks, null for global tasks', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_tasks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['status'], name='threadline__status_4ce4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['email_source'], name='threadline__email_s_23a036_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['status', 'created_at'], name='threadline__status_a54752_idx'),
        ),
    ]
