# Generated by Django 5.1.4 on 2025-09-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0003_add_unified_email_fetch_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailtask',
            name='threadline__user_id_b8c431_idx',
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='user',
        ),
    ]
