# Generated by Django 5.1.4 on 2025-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0004_populate_safe_filenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='processing_stage',
            field=models.CharField(blank=True, db_index=True, help_text='Current processing stage for detailed workflow tracking', max_length=50, null=True, verbose_name='Processing Stage'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='stage_progress',
            field=models.IntegerField(default=0, help_text='Progress percentage for current stage (0-100)', verbose_name='Stage Progress'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='stage_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current stage started processing', null=True, verbose_name='Stage Started At'),
        ),
    ]
