# Generated by Django 5.1.4 on 2025-10-03 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0004_remove_user_from_email_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailalias',
            name='threadline__alias_510f14_idx',
        ),
        migrations.AlterUniqueTogether(
            name='emailalias',
            unique_together={('alias',)},
        ),
        migrations.AlterField(
            model_name='emailalias',
            name='alias',
            field=models.CharField(help_text='Email alias name (domain is auto-assigned)', max_length=255, verbose_name='Alias'),
        ),
        migrations.AddIndex(
            model_name='emailalias',
            index=models.Index(fields=['alias'], name='threadline__alias_4bf954_idx'),
        ),
        migrations.RemoveField(
            model_name='emailalias',
            name='domain',
        ),
    ]
