# Generated by Django 5.1.4 on 2025-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0005_emailmessage_processing_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='stage_progress',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='stage_started_at',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='processing_stage',
            field=models.CharField(blank=True, db_index=True, help_text='Current processing stage (e.g., ocr_processing, jira_creation)', max_length=50, null=True, verbose_name='Processing Stage'),
        ),
    ]
