# Generated by Django 5.1.4 on 2025-10-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0005_remove_emailalias_threadline__alias_510f14_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('fetched', 'Fetched'), ('fetched_failed', 'Fetched Failed'), ('ocr_processing', 'Ocr Processing'), ('ocr_success', 'Ocr Success'), ('ocr_failed', 'Ocr Failed'), ('llm_ocr_processing', 'Llm Ocr Processing'), ('llm_ocr_success', 'Llm Ocr Success'), ('llm_ocr_failed', 'Llm Ocr Failed'), ('llm_email_processing', 'Llm Email Processing'), ('llm_email_success', 'Llm Email Success'), ('llm_email_failed', 'Llm Email Failed'), ('llm_summary_processing', 'Llm Summary Processing'), ('llm_summary_success', 'Llm Summary Success'), ('llm_summary_failed', 'Llm Summary Failed'), ('issue_processing', 'Issue Processing'), ('issue_success', 'Issue Success'), ('issue_failed', 'Issue Failed'), ('completed', 'Completed')], db_index=True, default='fetched', max_length=32, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='email_source',
            field=models.CharField(choices=[('IMAP_EMAIL_FETCH', 'IMAP Email Fetch'), ('HARAKA_EMAIL_FETCH', 'Haraka Email Fetch'), ('INBOX_CLEANUP', 'Inbox Cleanup'), ('PROCESSED_CLEANUP', 'Processed Cleanup'), ('FAILED_CLEANUP', 'Failed Cleanup'), ('TASK_CLEANUP', 'EmailTask Cleanup')], default='IMAP_EMAIL_FETCH', help_text='Type of email source being processed', max_length=20, verbose_name='Email Source'),
        ),
    ]
