# Generated by Django 5.1.4 on 2025-10-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0006_add_cleanup_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtask',
            name='email_source',
            field=models.CharField(choices=[('IMAP_EMAIL_FETCH', 'IMAP Email Fetch'), ('HARAKA_EMAIL_FETCH', 'Haraka Email Fetch'), ('HARAKA_CLEANUP', 'Haraka Cleanup'), ('TASK_CLEANUP', 'EmailTask Cleanup')], default='IMAP_EMAIL_FETCH', help_text='Type of email source being processed', max_length=20, verbose_name='Email Source'),
        ),
    ]
