# Generated by Django 5.1.4 on 2025-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0007_update_cleanup_task_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='emailtask',
            name='threadline__email_s_23a036_idx',
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='email_source',
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='emails_created_issues',
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='emails_processed',
        ),
        migrations.RemoveField(
            model_name='emailtask',
            name='timeout_seconds',
        ),
        migrations.AddField(
            model_name='emailtask',
            name='task_type',
            field=models.CharField(choices=[('IMAP_EMAIL_FETCH', 'IMAP Email Fetch'), ('HARAKA_EMAIL_FETCH', 'Haraka Email Fetch'), ('HARAKA_CLEANUP', 'Haraka Cleanup'), ('TASK_CLEANUP', 'EmailTask Cleanup')], default='IMAP_EMAIL_FETCH', help_text='Type of task being executed', max_length=20, verbose_name='Task Type'),
        ),
        migrations.AddIndex(
            model_name='emailtask',
            index=models.Index(fields=['task_type'], name='threadline__task_ty_fb8af3_idx'),
        ),
    ]
