# Generated by Django 5.1.4 on 2025-10-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0007_migrate_to_simplified_statuses'),
        ('threadline', '0008_alter_emailtask_options_and_more'),
    ]

    operations = [
    ]
