# Generated by Django 5.1.4 on 2025-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0009_merge_20251010_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('fetched', 'Fetched'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('completed', 'Completed')], db_index=True, default='fetched', max_length=32, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='task_type',
            field=models.CharField(choices=[('IMAP_EMAIL_FETCH', 'IMAP Email Fetch'), ('HARAKA_EMAIL_FETCH', 'Haraka Email Fetch'), ('HARAKA_CLEANUP', 'Haraka Cleanup'), ('TASK_CLEANUP', 'EmailTask Cleanup')], help_text='Type of task being executed', max_length=20, verbose_name='Task Type'),
        ),
    ]
