# Generated by Django 5.1.4 on 2025-10-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0011_remove_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('fetched', 'Fetched'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='fetched', max_length=32, verbose_name='Processing Status'),
        ),
    ]
