# Generated by Django 5.1.4 on 2025-10-12 15:43

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    """
    Convert existing PENDING and SKIPPED statuses to CANCELLED
    """
    EmailTask = apps.get_model('threadline', 'EmailTask')

    updated_count = EmailTask.objects.filter(
        status__in=['pending', 'skipped']
    ).update(status='cancelled')

    if updated_count > 0:
        print(f"Migrated {updated_count} tasks from pending/skipped to cancelled")


def reverse_migrate_statuses(apps, schema_editor):
    """
    Reverse migration: no-op as we cannot reliably restore old statuses
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0012_alter_emailmessage_status'),
    ]

    operations = [
        migrations.RunPython(
            migrate_old_statuses,
            reverse_migrate_statuses
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20, verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='task_type',
            field=models.CharField(choices=[('IMAP_EMAIL_FETCH', 'IMAP Email Fetch'), ('HARAKA_EMAIL_FETCH', 'Haraka Email Fetch'), ('HARAKA_CLEANUP', 'Haraka Cleanup'), ('TASK_CLEANUP', 'EmailTask Cleanup'), ('STUCK_EMAIL_RESET', 'Stuck Email Reset')], help_text='Type of task being executed', max_length=20, verbose_name='Task Type'),
        ),
    ]
