# Generated by Django 5.1.4 on 2025-10-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0013_remove_pending_skipped_add_stuck_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='task',
        ),
    ]
