# Generated by Django 5.1.4 on 2025-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0014_remove_emailmessage_task_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='fetch_retry_count',
            field=models.IntegerField(default=0, help_text='Number of times workflow trigger has been retried for emails stuck in FETCHED status', verbose_name='Fetch Retry Count'),
        ),
    ]
