# Generated by Django 5.1.4 on 2025-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0015_add_fetch_retry_count_to_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Unique identifier for external references', null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Unique identifier for external references', null=True, unique=True, verbose_name='UUID'),
        ),
    ]
