# Generated by Django 5.1.4 on 2025-10-22 08:58

import uuid
from django.db import migrations


def populate_uuids(apps, schema_editor):
    """
    Populate UUID fields for existing records
    """
    EmailMessage = apps.get_model('threadline', 'EmailMessage')
    EmailAttachment = apps.get_model('threadline', 'EmailAttachment')

    # Populate EmailMessage UUIDs
    for email in EmailMessage.objects.filter(uuid__isnull=True):
        email.uuid = uuid.uuid4()
        email.save(update_fields=['uuid'])

    # Populate EmailAttachment UUIDs
    for attachment in EmailAttachment.objects.filter(uuid__isnull=True):
        attachment.uuid = uuid.uuid4()
        attachment.save(update_fields=['uuid'])


def reverse_populate_uuids(apps, schema_editor):
    """
    Reverse migration: set UUIDs to null
    """
    EmailMessage = apps.get_model('threadline', 'EmailMessage')
    EmailAttachment = apps.get_model('threadline', 'EmailAttachment')

    EmailMessage.objects.all().update(uuid=None)
    EmailAttachment.objects.all().update(uuid=None)


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0016_add_uuid_fields'),
    ]

    operations = [
        migrations.RunPython(populate_uuids, reverse_populate_uuids),
    ]
