# Generated by Django 5.1.4 on 2025-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0017_populate_uuid_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured metadata for intelligent search and filtering', verbose_name='Metadata'),
        ),
    ]
