# Generated by Django 5.1.4 on 2025-11-02 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0019_repopulate_missing_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for external references', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for external references', unique=True, verbose_name='UUID'),
        ),
    ]
