# Generated by Django 5.1.4 on 2025-11-18 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0020_alter_emailattachment_uuid_alter_emailmessage_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='TODO item content', verbose_name='Content')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this TODO is completed', verbose_name='Is Completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when TODO was marked as completed', null=True, verbose_name='Completed At')),
                ('priority', models.CharField(blank=True, help_text='Priority level: high, medium, or low', max_length=20, null=True, verbose_name='Priority')),
                ('owner', models.CharField(blank=True, help_text='Person responsible for this TODO', max_length=255, null=True, verbose_name='Owner')),
                ('deadline', models.DateTimeField(blank=True, help_text='Deadline for this TODO', null=True, verbose_name='Deadline')),
                ('location', models.CharField(blank=True, help_text='Location related to this TODO', max_length=255, null=True, verbose_name='Location')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for this TODO', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email_message', models.ForeignKey(blank=True, help_text='Related email message (null for manually created TODOs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='threadline.emailmessage', verbose_name='Email Message')),
                ('user', models.ForeignKey(help_text='User who owns this TODO', on_delete=django.db.models.deletion.CASCADE, related_name='email_todos', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email TODO',
                'verbose_name_plural': 'Email TODOs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='threadline__user_id_67a37a_idx'), models.Index(fields=['email_message'], name='threadline__email_m_884da2_idx'), models.Index(fields=['deadline'], name='threadline__deadlin_04d7f9_idx'), models.Index(fields=['priority'], name='threadline__priorit_89e385_idx')],
            },
        ),
    ]
