# Generated by Django 5.1.4 on 2025-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0021_add_email_todo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='summary_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured summary data containing details and key_process. TODO items are stored separately in EmailTodo model.', verbose_name='Summary Data'),
        ),
    ]
