# Generated by Django 5.1.4 on 2025-11-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0022_add_summary_data_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='raw_content',
        ),
    ]
