# Generated by Django 5.1.4 on 2025-11-25 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0023_remove_raw_content_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadlineShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('password_hash', models.CharField(blank=True, max_length=128, verbose_name='Password Hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Viewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='threadline.emailmessage', verbose_name='Email Message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadline_share_links', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Threadline Share Link',
                'verbose_name_plural': 'Threadline Share Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uuid'], name='threadline__uuid_7b5bf0_idx'), models.Index(fields=['email_message'], name='threadline__email_m_aefeed_idx'), models.Index(fields=['owner'], name='threadline__owner_i_aed615_idx'), models.Index(fields=['is_active'], name='threadline__is_acti_9a33f9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email_message',), name='unique_active_share_per_email')],
            },
        ),
    ]
