# Generated by Django 5.1.4 on 2025-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0024_threadlinesharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadlinesharelink',
            name='password',
            field=models.CharField(blank=True, max_length=12, verbose_name='Password'),
        ),
    ]
