# Generated by Django 5.1.4 on 2025-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0025_add_password_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadlinesharelink',
            name='password',
            field=models.CharField(blank=True, max_length=6, verbose_name='Password'),
        ),
    ]
