# Generated by Django 5.1.4 on 2026-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threadline", "0028_threadlineworkflowconfig_dual_llm_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("IMAP_EMAIL_FETCH", "IMAP Email Fetch"),
                    ("HARAKA_EMAIL_FETCH", "Haraka Email Fetch"),
                    ("EMAIL_WORKFLOW", "Email Workflow"),
                    ("HARAKA_CLEANUP", "Haraka Cleanup"),
                    ("TASK_CLEANUP", "EmailTask Cleanup"),
                    ("STUCK_EMAIL_RESET", "Stuck Email Reset"),
                ],
                help_text="Type of task being executed",
                max_length=20,
                verbose_name="Task Type",
            ),
        ),
    ]
