# Generated by Codex on 2026-04-28

from django.db import migrations, models
import django.db.models.deletion


def populate_display_state(apps, schema_editor):
    """
    Backfill display_state for historical rows.
    """
    EmailMessage = apps.get_model("threadline", "EmailMessage")

    for email in EmailMessage.objects.all().only("id", "status"):
        if email.status in {"success", "failed"}:
            display_state = "canonical"
        else:
            display_state = "processing"
        EmailMessage.objects.filter(pk=email.pk).update(
            display_state=display_state
        )


class Migration(migrations.Migration):
    dependencies = [
        ("threadline", "0029_alter_emailtask_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="display_state",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("canonical", "Canonical"),
                    ("merged", "Merged"),
                ],
                db_index=True,
                default="processing",
                help_text="UI state for threadline display",
                max_length=32,
                verbose_name="Display State",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="in_reply_to",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="RFC In-Reply-To header extracted from the source email",
                max_length=255,
                verbose_name="In Reply To",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="last_merged_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp of the latest merge into this record",
                verbose_name="Last Merged At",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="merge_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("thread_relation", "Thread Relation"),
                    ("forward_chain", "Forward Chain"),
                    ("text_similarity", "Text Similarity"),
                ],
                default="",
                help_text="Why this record was merged into another record",
                max_length=32,
                verbose_name="Merge Reason",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical email message that absorbed this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_children",
                to="threadline.emailmessage",
                verbose_name="Merged Into",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="raw_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="RFC Message-ID header extracted from the source email",
                max_length=255,
                verbose_name="Raw Message ID",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="references",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Normalized References header tokens",
                verbose_name="References",
            ),
        ),
        migrations.RunPython(
            code=populate_display_state,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["user", "display_state"],
                name="em_user_disp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["user", "raw_message_id"],
                name="em_user_rawmsg_idx",
            ),
        ),
    ]
