# Generated by Codex on 2026-04-28

import hashlib
import os

from django.db import migrations, models


def compute_md5(file_path):
    digest = hashlib.md5()
    with open(file_path, "rb") as file_handle:
        for chunk in iter(lambda: file_handle.read(8192), b""):
            digest.update(chunk)
    return digest.hexdigest()


def populate_content_md5(apps, schema_editor):
    """
    Backfill attachment hashes for historical rows when the file still exists.
    """
    EmailAttachment = apps.get_model("threadline", "EmailAttachment")

    queryset = EmailAttachment.objects.filter(content_md5="")
    for attachment in queryset.iterator():
        file_path = attachment.file_path
        if not file_path or not os.path.exists(file_path):
            continue

        try:
            EmailAttachment.objects.filter(pk=attachment.pk).update(
                content_md5=compute_md5(file_path)
            )
        except OSError:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("threadline", "0030_emailmessage_merge_and_display_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailattachment",
            name="content_md5",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="MD5 hash of the attachment content",
                max_length=32,
                verbose_name="Content MD5",
            ),
        ),
        migrations.RunPython(
            code=populate_content_md5,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["user", "content_md5"],
                name="ea_user_md5_idx",
            ),
        ),
    ]
