# Generated by Django 5.1.4 on 2026-04-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadline', '0031_emailattachment_content_md5_and_cache_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailattachment',
            new_name='threadline__user_id_12453c_idx',
            old_name='ea_user_md5_idx',
        ),
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='threadline__user_id_708251_idx',
            old_name='em_user_disp_idx',
        ),
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='threadline__user_id_86ebf3_idx',
            old_name='em_user_rawmsg_idx',
        ),
    ]
