# Generated by Django 5.1.4 on 2026-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threadline", "0035_remove_emailmessage_merge_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="merge_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("thread_relation", "Thread Relation"),
                    ("forward_chain", "Forward Chain"),
                    ("text_similarity", "Text Similarity"),
                    ("manual", "Manual"),
                ],
                default="",
                help_text="Why this record was merged into another record",
                max_length=32,
                verbose_name="Merge Reason",
            ),
        ),
    ]
