# Generated by Django 5.1.4 on 2026-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threadline", "0036_alter_emailmessage_merge_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="merge_evidence",
            field=models.JSONField(
                blank=True,
                help_text="Discriminating evidence for the merge decision (matcher, similarity scores, matched message-id/fields), for auditing.",
                null=True,
                verbose_name="Merge Evidence",
            ),
        ),
    ]
