# Generated by Django 5.1.4 on 2025-11-02 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0002_2_10'),
        ('threadline', '0020_alter_emailattachment_uuid_alter_emailmessage_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'stripe', 'alipay', 'wechat'", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Provider',
                'verbose_name_plural': 'Payment Providers',
                'db_table': 'billing_payment_provider',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('monthly_price_cents', models.IntegerField(help_text='Price in cents (e.g., 2999 for $29.99)')),
                ('metadata', models.JSONField(default=dict, help_text='Flexible configuration: credits_per_period, period_days, workflow_cost_credits, max_email_length, max_attachment_count, storage_quota_mb')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'billing_plan',
                'ordering': ['monthly_price_cents'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('trialing', 'Trialing'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('djstripe_subscription', models.ForeignKey(blank=True, help_text='Link to dj-stripe Subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.paymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'billing_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='billing.paymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'db_table': 'billing_payment_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_credits', models.IntegerField(default=0, help_text='Credits from subscription plan')),
                ('bonus_credits', models.IntegerField(default=0, help_text='Bonus credits from promotions or compensation')),
                ('consumed_credits', models.IntegerField(default=0, help_text='Total credits consumed in current period')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('djstripe_customer', models.ForeignKey(blank=True, help_text='Link to dj-stripe Customer for sync', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credits', to='billing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credits',
                'verbose_name_plural': 'User Credits',
                'db_table': 'billing_user_credits',
            },
        ),
        migrations.CreateModel(
            name='CreditsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('grant', 'Grant'), ('bonus', 'Bonus'), ('compensation', 'Compensation'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_credits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credits Transaction',
                'verbose_name_plural': 'Credits Transactions',
                'db_table': 'billing_credits_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_type', 'created_at'], name='billing_cre_user_id_0a07da_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailCreditsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('consume', 'Consume'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.IntegerField(default=1)),
                ('reason', models.CharField(default='workflow_execution', max_length=500)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Idempotency key format: email_{uuid}_workflow_execution or email_{uuid}_retry_{timestamp}', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_transactions', to='threadline.emailmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_credits_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Credits Transaction',
                'verbose_name_plural': 'Email Credits Transactions',
                'db_table': 'billing_email_credits_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_type', 'created_at'], name='billing_ema_user_id_312e48_idx'), models.Index(fields=['idempotency_key'], name='billing_ema_idempot_b566a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailWorkflowUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_uuid', models.UUIDField(db_index=True, help_text='UUID for idempotency across environments', unique=True)),
                ('llm_call_count', models.IntegerField(default=0)),
                ('llm_success_count', models.IntegerField(default=0)),
                ('llm_total_input_tokens', models.IntegerField(default=0)),
                ('llm_total_output_tokens', models.IntegerField(default=0)),
                ('llm_total_tokens', models.IntegerField(default=0)),
                ('ocr_call_count', models.IntegerField(default=0)),
                ('ocr_success_count', models.IntegerField(default=0)),
                ('ocr_total_images', models.IntegerField(default=0)),
                ('llm_calls_detail', models.JSONField(default=list, help_text='List of all LLM calls with tokens, success status, errors')),
                ('ocr_calls_detail', models.JSONField(default=list, help_text='List of all OCR calls with filenames, success status, errors')),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost based on pricing config', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_usage', to='threadline.emailmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_workflow_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Workflow Usage',
                'verbose_name_plural': 'Email Workflow Usages',
                'db_table': 'billing_email_workflow_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='billing_ema_user_id_a02bde_idx'), models.Index(fields=['email_message_uuid'], name='billing_ema_email_m_7eff84_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_product_id', models.CharField(help_text='Stripe Product ID', max_length=255)),
                ('provider_price_id', models.CharField(help_text='Stripe Price ID', max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('unit_amount_cents', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_prices', to='billing.plan')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_prices', to='billing.paymentprovider')),
            ],
            options={
                'verbose_name': 'Plan Price',
                'verbose_name_plural': 'Plan Prices',
                'db_table': 'billing_plan_price',
                'unique_together': {('plan', 'provider', 'interval')},
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'current_period_end'], name='billing_sub_user_id_3ed20e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['provider_payment_id'], name='billing_pay_provide_1bdf50_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredits',
            index=models.Index(fields=['user', 'is_active'], name='billing_use_user_id_e84af2_idx'),
        ),
    ]
