# Generated by Django 5.1.4 on 2025-11-15 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_refactor_email_workflow_usage_onetoone'),
        ('djstripe', '0002_2_10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercredits',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_user_credits'),
        ),
    ]
