# Generated by Django 5.1.4 on 2025-11-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_usercredits_unique_active_user_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal plan for staff/partners, not visible to public'),
        ),
    ]
