# Generated by Django 5.1.4 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_is_internal_to_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'singleton_key',
                    models.CharField(default='default', max_length=32, unique=True),
                ),
                ('stripe_live_mode', models.BooleanField(default=False)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=255)),
                ('stripe_live_secret_key', models.TextField(blank=True, default='')),
                ('stripe_test_secret_key', models.TextField(blank=True, default='')),
                ('stripe_webhook_secret', models.TextField(blank=True, default='')),
                ('default_free_credits', models.IntegerField(default=10)),
                ('workflow_cost_credits', models.IntegerField(default=1)),
                ('auto_refund_system_errors', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Config',
                'verbose_name_plural': 'Billing Config',
                'db_table': 'billing_config',
                'ordering': ['-updated_at'],
            },
        ),
    ]
