# Generated by Django 5.1.4 on 2026-05-17 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_billingconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the operator name at write time",
                        max_length=150,
                    ),
                ),
                (
                    "target_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the target user name at write time",
                        max_length=150,
                    ),
                ),
                ("action_type", models.CharField(db_index=True, max_length=64)),
                (
                    "source",
                    models.CharField(db_index=True, default="system", max_length=32),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("before_data", models.JSONField(default=dict)),
                ("after_data", models.JSONField(default=dict)),
                ("context", models.JSONField(default=dict)),
                (
                    "event_key",
                    models.CharField(
                        db_index=True,
                        help_text="Idempotency key for audit write retries",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_audit_logs_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Audit Log",
                "verbose_name_plural": "Billing Audit Logs",
                "db_table": "billing_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="billing_aud_action__c0c8dd_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="billing_aud_source_159982_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="billing_aud_target__939fdc_idx",
                    ),
                ],
            },
        ),
    ]
