# Generated by Django 5.1.4 on 2025-07-21 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key name', max_length=100, verbose_name='Setting Key')),
                ('value', models.JSONField(help_text='Configuration value (JSON format)', verbose_name='Setting Value')),
                ('description', models.CharField(blank=True, help_text='Description of this setting', max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['user', 'key'],
            },
        ),
        migrations.DeleteModel(
            name='JiraSettings',
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['user', 'key'], name='jirabot_set_user_id_9b038e_idx'),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['is_active'], name='jirabot_set_is_acti_98c632_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='settings',
            unique_together={('user', 'key')},
        ),
    ]
