# Generated by Django 5.1.4 on 2025-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0002_settings_delete_jirasettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='ocr_content',
            field=models.TextField(blank=True, help_text='Text content recognized from image attachment', null=True, verbose_name='OCR Content'),
        ),
    ]
