# Generated by Django 5.1.4 on 2025-07-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0003_emailattachment_ocr_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('summary_processing', 'Summary Processing'), ('summary_failed', 'Summary Failed'), ('summary_success', 'Summary Success'), ('issue_processing', 'Issue Processing'), ('issue_failed', 'Issue Failed'), ('issue_created', 'Issue Created'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Processing Status'),
        ),
    ]
