# Generated by Django 5.1.4 on 2025-07-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0004_alter_emailmessage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jiraissue',
            name='jirabot_jir_user_id_64b011_idx',
        ),
        migrations.RemoveIndex(
            model_name='jiraissue',
            name='jirabot_jir_user_id_e553f0_idx',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='jira_issue_id',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='status',
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='email_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='jirabot.emailmessage', verbose_name='Email Message'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['user', 'email_message'], name='jirabot_jir_user_id_106619_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['jira_issue_key'], name='jirabot_jir_jira_is_55f7cb_idx'),
        ),
    ]
