# Generated by Django 5.1.4 on 2025-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0005_remove_jiraissue_jirabot_jir_user_id_64b011_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('ocr_processing', 'OCR Processing'), ('ocr_failed', 'OCR Failed'), ('ocr_success', 'OCR Success'), ('summary_processing', 'Summary Processing'), ('summary_failed', 'Summary Failed'), ('summary_success', 'Summary Success'), ('jira_processing', 'JIRA Processing'), ('jira_failed', 'JIRA Failed'), ('jira_success', 'JIRA Success'), ('attachment_uploading', 'Attachment Uploading'), ('attachment_upload_failed', 'Attachment Upload Failed'), ('attachment_uploaded', 'Attachment Uploaded'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=32, verbose_name='Processing Status'),
        ),
    ]
