# Generated by Django 5.1.4 on 2025-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0006_alter_emailmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='llm_content',
            field=models.TextField(blank=True, help_text='Content organized by large language model', null=True, verbose_name='LLM Processed Content'),
        ),
    ]
