# Generated by Django 5.1.4 on 2025-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirabot', '0007_emailmessage_llm_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='llm_content',
            field=models.TextField(blank=True, help_text='Content organized by large language model based on OCR result', null=True, verbose_name='LLM Processed Content'),
        ),
    ]
